### ISSUE TITLE
❌ MOBILISTEN » INITIALIZATION FAILED: INVALID RESOURCE

### ISSUE THREAD

**Issue by diadal** [zoho/SalesIQ-Mobilisten-Cordova#14]
Error ❌ MOBILISTEN » INITIALIZATION FAILED: INVALID RESOURCE on ios `appKey` and `accessKey` keys matched viewed from the console log

```
  let appKey;
  let accessKey;
  if (box.$q.platform.is.ios) {
    appKey = process.env.VITE_ZOHO_KEY_IOS;
    accessKey = process.env.VITE_ZOHO_ACCESS_IOS;
  } else {
    appKey = process.env.VITE_ZOHO_KEY;
    accessKey = process.env.VITE_ZOHO_ACCESS;
  }

  box.$ZohoSalesIQ.init(appKey, accessKey, (success) => {
    console.log('success: ', success);
    //Use the ZohoSalesIQ.Launcher.show API if you wish to show the launcher by default.
    // box.$ZohoSalesIQ.Launcher.show(VisibilityMode.ALWAYS);
    box.$ZohoSalesIQ.Launcher.show(
      box.$ZohoSalesIQ.Launcher.VisibilityMode.ALWAYS,
    );
  });
}

```

**Comment by venkatesh-ramesh-12517** [comment]
Hi @diadal 
 
Thank you for reaching out to us.
 
This issue may occur due to the incorrect appKey, accessKey, and bundle ID. Please ensure that you are using the correct iOS appKey, accessKey, and bundle ID.
 
To verify keys, open SalesIQ and navigate to _Settings > Brands > Select the Brand > Installation > iOS_. Ensure that the correct keys and bundleID are passed in the initialization call.
 
If you have any further inquiries, please do not hesitate to reach out to our dedicated support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com)
 
Regards,
Venkatesh R,
Zoho SalesIQ.
