### ISSUE TITLE
How can chat be opened using an on click event?

### ISSUE THREAD

**Issue by ebofi** [zoho/SalesIQ-Mobilisten-Cordova#3]
Hi, 

How we can call the chat using a onclick event. We try for launcher true method, but no luck... Could you explain

**Comment by Rishabh-Raghunath** [comment]
Hi @ebofi, You may use the [**`ZohoSalesIQ.show()`**](https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-sdk-open-chat-.html) API to pop open chat/the Mobilisten UI in response to an onclick event from a button of your choice. 

The [**`ZohoSalesIQ.showLauncher`**](https://www.zoho.com/salesiq/help/developer-section/cordova-ionic-sdk-set-launcher-visibility.html) API is used to hide/show the default launcher. I assume showing the default launcher would not be needed in your case and thus invoking this API would not be required.

**Comment by Angu-G** [comment]
> We try for launcher true method, but no luck

Hello @ebofi, Hope this flow is working now. Since you have used wrong **appKey** in the init() API call, Mobilisten was not initialized and hence this method wasn't working which was explained by our support representative when you reached them. We are closing this issue now. You can write back for further queries.
